In [57]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [58]:
df = pd.read_csv('Churn_Modelling.csv')
df.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [59]:
df = df.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [60]:
df.head()

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1
3          699    France  Female  ...               0         93826.63       0
4          850     Spain  Female  ...               1         79084.10       0

[5 rows x 11 columns]

In [61]:
label_encoder = LabelEncoder()
df['Gender'] = label_encoder.fit_transform(df['Gender'])
df

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France       0  ...               1        101348.88       1
1             608     Spain       0  ...               1        112542.58       0
2             502    France       0  ...               0        113931.57       1
3             699    France       0  ...               0         93826.63       0
4             850     Spain       0  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France       1  ...               0         96270.64       0
9996          516    France       1  ...               1        101699.77       0
9997          709    France       0  ...               1         42085.58       1
9998          772   Germany       1  ...               0         92888.52       1
9999          792    France       0  ...               0         38190.78       0

[10000 rows x 11 columns]

In [62]:
from sklearn.preprocessing import OneHotEncoder
onehot_encoder = OneHotEncoder()
geo_encoded = onehot_encoder.fit_transform(df[['Geography']])
geo_encoded.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], shape=(10000, 3))

In [63]:
pd.DataFrame(geo_encoded.toarray(), columns=onehot_encoder.get_feature_names_out(['Geography']))
df = pd.concat([df, pd.DataFrame(geo_encoded.toarray(), columns=onehot_encoder.get_feature_names_out(['Geography']))], axis=1)

In [64]:
df.drop(['Geography'], axis=1, inplace=True)
df.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [65]:
with open('onehot_encoder.pkl', 'wb') as f:
    pickle.dump(onehot_encoder, f)

In [66]:
with open('label_encoder.pkl', 'wb') as f:
    pickle.dump(label_encoder, f)

In [67]:
X = df.drop(['Exited'], axis=1)
y = df['Exited']

In [68]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [69]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [70]:
with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

In [71]:
df

      CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0             619       0  ...                0.0              0.0
1             608       0  ...                0.0              1.0
2             502       0  ...                0.0              0.0
3             699       0  ...                0.0              0.0
4             850       0  ...                0.0              1.0
...           ...     ...  ...                ...              ...
9995          771       1  ...                0.0              0.0
9996          516       1  ...                0.0              0.0
9997          709       0  ...                0.0              0.0
9998          772       1  ...                1.0              0.0
9999          792       0  ...                0.0              0.0

[10000 rows x 13 columns]

In [75]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [77]:
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

In [78]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [79]:
import tensorflow
opt = tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss = tensorflow.keras.losses.BinaryCrossentropy()

In [80]:
model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['accuracy'])

In [81]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [83]:

early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [85]:
history = model.fit(X_train, y_train, epochs=10, validation_data=(X_test, y_test), callbacks=[early_stopping_callback, tensorboard_callback])

Epoch 1/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8572 - loss: 0.3451 - val_accuracy: 0.8585 - val_loss: 0.3421
Epoch 2/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8624 - loss: 0.3398 - val_accuracy: 0.8610 - val_loss: 0.3427
Epoch 3/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8639 - loss: 0.3365 - val_accuracy: 0.8605 - val_loss: 0.3436
Epoch 4/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8641 - loss: 0.3343 - val_accuracy: 0.8580 - val_loss: 0.3443
Epoch 5/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.8630 - loss: 0.3327 - val_accuracy: 0.8580 - val_loss: 0.3438
Epoch 6/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.8660 - loss: 0.3305 - val_accuracy: 0.8600 - val_loss: 0.3438
Epoch 7/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.8674 - loss: 0.3295 - val_accuracy: 0.8605 - val_loss: 0.3500
Epoch 8/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.8696 - loss: 0.3278 - val_accuracy: 0.8600 - val_loss: 0.3502
Epoch 9/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.8698 - loss: 0.3259 - val_accuracy: 0.8555 - val_loss: 0.3528
Epoch 10/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.8704 - loss: 0.3224 - val_accuracy: 0.8525 - val_loss: 0.3599

In [87]:
model.save('model.keras')